name: CI
on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.projectKey=Java_PR_Automation \
        -Dsonar.host.url=http://localhost9000 \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}