name: Auto Merge PR

on:
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR number
        id: get_pr
        run: echo "::set-output name=pr_number::$(jq -r '.check_suite.pull_requests[0].number' <<< "$GITHUB_EVENT")"
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}

      - name: Merge PR
        run: |
          gh pr merge ${{ steps.get_pr.outputs.pr_number }} --merge --admin --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
