name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: ${{ runner.os }}-sonar-cache

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=python \
            -Dsonar.host.url=https://abfc-116-74-252-253.ngrok-free.app/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        id: check_quality_gate
        run: |
          qualityGateStatus=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://abfc-116-74-252-253.ngrok-free.app/api/qualitygates/project_status?projectKey=my_project_key" \
            | jq -r '.projectStatus.status')
          echo "::set-output name=status::$qualityGateStatus"

      - name: Fail if Quality Gate is not passed
        if: steps.check_quality_gate.outputs.status != 'OK'
        run: exit 1
