name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=python \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://abfc-116-74-252-253.ngrok-free.app/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        id: check_quality_gate
        run: |
          qualityGateStatus=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://abfc-116-74-252-253.ngrok-free.app/api/qualitygates/project_status?projectKey=my_project_key" \
            | jq -r '.projectStatus.status')
          echo "::set-output name=status::$qualityGateStatus"

      - name: Fail if Quality Gate is not passed
        if: steps.check_quality_gate.outputs.status != 'OK'
        run: exit 1
